### ISSUE TITLE
Crear pantalla de artista

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#11]
Crear la pantalla de artista, mostrar sus álbums y la opción de suscribirse a ellos.

**Comment by ghost** [comment]
Pantalla terminada, falta revisión de @Alvarogd6 para que cierre la issue.
Por ahora no se necesita iniciar sesion para verla, se encuentra en `localhost:4200/artist`

**Comment by Alvarogd6** [comment]
Ya se puede consultar los álbums de un artista. Ahora se necesita iniciar sesión para verla. Issue cerrada
