### ISSUE TITLE
Solucionar problemas de podcasts

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#23]
- [x] En algunos casos, cuando la descripción es bastante grande, al mostrar los podcasts, se mezclan las letras con el siguiente podcast y no se entiende nada
- [x] Crear el botón para añadir una lista de podcasts a favoritos
- [x] Añadir a la cola toda la lista de podcasts
- [x] Búsqueda de podcasts mediante ids
- [x] Añadir un podcast individual a la cola

**Comment by Alvarogd6** [comment]
Botón creado para añadir a favoritos, falta esperar a backend a implementar los cambios necesarios.

**Comment by ghost** [comment]
Creada pantalla inicial de podcasts con los podcasts favoritos, falta revision de @Alvarogd6 

Falta también la implementacion de guardar un podcast en favoritos, existe el boton pero no el codigo.

**Comment by Alvarogd6** [comment]
Terminadas todas las opciones de podcast. Issue cerrada
