### ISSUE TITLE
Crear la pantalla información

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#28]
Diseño de la pantalla información, que será la primera en mostrarse cuando no se haya iniciado sesión un usuario. Su principal función es informar al usuario sobre lo que trata la web y permitir redireccionar a las pantallas de registro, inicio sesión y ayuda.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/44313461/81495845-93852800-92b3-11ea-93bf-7cf1a5c2d801.png)

Presioso, falta revision de @Alvarogd6

**Comment by Alvarogd6** [comment]
Pantalla principal con redirrecciones a iniciar sesión y registro con diseño completada. Issue cerrada
