### ISSUE TITLE
Diseño de la web

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#31]
Mejorar el diseño de la web cambiando los colores y cambiando algunos elementos

**Comment by Alvarogd6** [comment]
Añadir al menú lateral la imagen del usuario y su nombre como mínimo y debajo de eso poner el buscador y los enlaces

**Comment by ghost** [comment]
Cambiado boton de eliminar busqueda en la pantalla de podcasts
Cambiado boton de añadir musica a la lista de reproduccion en la pantalla principal

**Comment by Alvarogd6** [comment]
Cambios a realizar:

1. Cabecera
    - En vez de TuneIT poner el logo con el texto a la derecha
    - Enlaces sin subrayado
    - Enlaces con más espacio entre ellos
2. Login y registro
    - Aparecen los dos scroll (horizontal y vertical) incluso cuando la web no ocupa toda la pantalla
    - En registro estaría bien que al clickar en fecha de nacimiento aparezca el calendario
    - Imagen de la fecha de nacimiento a la izquierda y añadir una para país (mantener consistencia con el resto del formulario)
3. Menú
    - Imagen y nombre centrados
    - Eliminar opción Listas de reproducción (mirar punto Música)
4. Amigos
    - Nombre y botones más separados de la imagen
    - Las 3 opciones (Amigos, solicitudes, buscar) estaría mejor así
![Untitled Diagram](https://user-images.githubusercontent.com/46053417/81992173-2969db80-9643-11ea-8607-a71e4f4f00fa.jpg)
5. Listas de reproducción (pantalla en la que se muestran todas las playlists)
    - Estilo de los botones y formularios
6. Podcasts
    - Al mostrar los podcasts favoritos, añadir un botón para eliminarlos
    - Al mostrar información de un episodio, centrar la imagen y el título. También centrar el texto del botón Buscar
    - A veces aparecen ... cuando la descripción es nula o muy corta
7. Música
    - La forma de mostrar las últimas canciones (se puede poner que se muestren unas cuantas y una flecha para mostrar las otras)
    - No mostrar el título de Artistas suscritos si no tiene ninguno
    - Añadir la pestaña Listas de reproducción (mismo estilo que las opciones de Amigos)
![Untitled Diagram(1)](https://user-images.githubusercontent.com/46053417/81992567-0db30500-9644-11ea-8ffb-dc5754986fa6.jpg)
8. Canción
    - Centrar la línea del volumen
    - Cambiar estilo (y puede que posición) de los botones Volver y Cola de reproducción
9. Web
    - Cambiar fondo (estudiar la posibilidad de un degradado/gradiente)
10. Artista
    - Cambiar estilo y posición del botón de suscripción

**Comment by ghost** [comment]
1. Cabecera
    - [x] En vez de TuneIT poner el logo con el texto a la derecha
    - [x] Enlaces sin subrayado
    - [x] Enlaces con más espacio entre ellos
2. Login y registro
    - [x] Aparecen los dos scroll (horizontal y vertical) incluso cuando la web no ocupa toda la pantalla
    - [x] En registro estaría bien que al clickar en fecha de nacimiento aparezca el calendario
    - [x] Imagen de la fecha de nacimiento a la izquierda y añadir una para país (mantener consistencia con el resto del formulario)
3. Menú
    - [x] Imagen y nombre centrados
    - [x] Eliminar opción Listas de reproducción (mirar punto Música)
4. Amigos
    - [x] Nombre y botones más separados de la imagen
   -  [x] Las 3 opciones (Amigos, solicitudes, buscar) estaría mejor así
![](https://user-images.githubusercontent.com/46053417/81992173-2969db80-9643-11ea-8607-a71e4f4f00fa.jpg)
5. Listas de reproducción (pantalla en la que se muestran todas las playlists) 
    - [x] Estilo de los botones y formularios
6. Podcasts
    - [x] Al mostrar los podcasts favoritos, añadir un botón para eliminarlos
    - [x] Al mostrar información de un episodio, centrar la imagen y el título. También centrar el texto del botón Buscar
    - [x] A veces aparecen `...` cuando la descripción es nula o muy corta(si tiene)
7. Música
    - [x] La forma de mostrar las últimas canciones (se puede poner que se muestren unas cuantas y una flecha para mostrar las otras)
    - [x] No mostrar el título de Artistas suscritos si no tiene ninguno
    - [x] Añadir la pestaña Listas de reproducción (mismo estilo que las opciones de Amigos)
![](https://user-images.githubusercontent.com/46053417/81992567-0db30500-9644-11ea-8ffb-dc5754986fa6.jpg)
8. Canción
    -  [x] Centrar la linea del volumen
    - [x] Cambiar estilo (y puede que posición) de los botones Volver y Cola de reproducción
9. Web
    - [x] Cambiar fondo (estudiar la posibilidad de un degradado/gradiente)
10. Artista
    - [x] Cambiar estilo y posición del botón de suscripción

**Comment by ghost** [comment]
En:
2. Registro
    - En registro estaría bien que al clickar en fecha de nacimiento aparezca el calendario

No se ha encontrado la forma de hacerlo, lo que se ha hecho ha sido hacer que el icono donde hay que clickar este sobresaltado
![image](https://user-images.githubusercontent.com/44313461/82036295-0706ab00-96a1-11ea-8fd9-80fb344240ad.png)
 y que no se pueda clickar en el campo de fecha para evitar asi fechas con formato erroneo.

**Comment by Alvarogd6** [comment]
2. Registro y Login
- Siguen apareciendo los dos scrolls

5. Listas de reproducción
- [x] Volver a poner el recuadro en las listas
- [ ] Volver a poner el texto de Favoritos en el centro del recuadro
- [x] Ambos formularios no hace falta que ocupen todo el ancho o más
- [x] Si alguna lista se sale de la pantalla, que se ponga debajo de las demás (como estaba antes)
- [x] En vez de volver, sería mejor presentar las dos opciones (Música y Listas de reproducción, como en la pantalla de Amigos)
![Captura de pantalla de 2020-05-15 14-12-50](https://user-images.githubusercontent.com/46053417/82049786-40e2ac00-96b7-11ea-974e-066fedf25202.png)

**Comment by ghost** [comment]
Me niego a volver a poner el recuadro ese en las listas, es feísimo  >:(

**Comment by ghost** [comment]
>     6. Podcasts
>        
>        * [ ]  Al mostrar los podcasts favoritos, añadir un botón para eliminarlos

Ya lo tienen, he cambiado el icono para que se vea mas claro.
Se accede a dicha posibilidad al clickar en el podcast

![image](https://user-images.githubusercontent.com/44313461/82117719-5e288080-9772-11ea-85da-47885e376f58.png)

**Comment by ghost** [comment]
> 7. Música
>    * [ ] La forma de mostrar las últimas canciones (se puede poner que se muestren unas cuantas y una flecha para mostrar las otras)

Al ser "ultimas canciones añadidas" no es mejor poner un numero fijo de canciones? Por ejemplo 3 o 4.

Ya que si no,  un usuario con muchas canciones tendra ahi una lista gigante ocupandole toda la pantalla

@Alvarogd6

**Comment by Alvarogd6** [comment]
Las últmas canciones añadidas no dependen del usuario, sino de la base de datos. Es un número fijo para todos (actualmente 8). Se puede cambiar ese número y si se salen de la pantalla, clickar en una flecha para acceder al resto.

**Comment by Alvarogd6** [comment]
> > ```
> > 6. Podcasts
> >    
> >    * [ ]  Al mostrar los podcasts favoritos, añadir un botón para eliminarlos
> > ```
> 
> Ya lo tienen, he cambiado el icono para que se vea mas claro.
> Se accede a dicha posibilidad al clickar en el podcast
> 
> ![image](https://user-images.githubusercontent.com/44313461/82117719-5e288080-9772-11ea-85da-47885e376f58.png)

Me referia al mostrar la lista de podcasts favoritos, antes de acceder a un podcast en concreto

**Comment by ghost** [comment]
> > > ```
> > > 6. Podcasts
> > >    
> > >    * [ ]  Al mostrar los podcasts favoritos, añadir un botón para eliminarlos
> > > ```
> > 
> > 
> > Ya lo tienen, he cambiado el icono para que se vea mas claro.
> > Se accede a dicha posibilidad al clickar en el podcast
> > ![image](https://user-images.githubusercontent.com/44313461/82117719-5e288080-9772-11ea-85da-47885e376f58.png)
> 
> Me referia al mostrar la lista de podcasts favoritos, antes de acceder a un podcast en concreto

Hecho! Tienes razon, mucho mas sencillo para el usuario

**Comment by Alvarogd6** [comment]
En los podcasts, el botón de eliminar también se encuentra en los podcasts no favoritos (por ejemplo, al realizar una búsqueda, aparecen todos los podcasts con el botón de eliminar y no tendría que aparecer) y en la pantalla de canción la línea del volumen sigue sin estar centrada al quitar el menú.

**Comment by Alvarogd6** [comment]
En la pantalla de playlists, al clickar en eliminar lista, te lleva a la pantalla lista de la lista eliminada, pero no deberia pasar ya que esa lista ha sido eliminada. El fondo en las pantallas de login y registro se ve blanco y blanco sucio.
![Captura de pantalla de 2020-05-22 13-12-32](https://user-images.githubusercontent.com/46053417/82662524-4f3c4500-9c2e-11ea-8d47-765cb4259645.png)
Quitar la línea que separa la cabecera y el menú
![Captura de pantalla de 2020-05-22 13-13-04](https://user-images.githubusercontent.com/46053417/82662561-5fecbb00-9c2e-11ea-958a-90676d481cd1.png)

**Comment by Alvarogd6** [comment]
Terminado el diseño de la web. Issue cerrada
