### ISSUE TITLE
Diseño de la pantalla perfil y configuración

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#32]
Diseño de la pantalla perfil en la que se muestra la información del usuario, su imagen y sus listas de reprodución. También habrá un botón para modificar la imagen y para modificar la información del usuario.

**Comment by ghost** [comment]
Pantalla terminada, falta revision de @Alvarogd6 para cerrar la issue. Faltaría darle estilo a la pantalla de configuración pero no se si corresponde a esta issue

**Comment by ghost** [comment]
Pantalla de configuración con estilo, me he sacado la polla @Alvarogd6 
![image](https://user-images.githubusercontent.com/44313461/80799649-b4f55e00-8ba7-11ea-9c3b-d35253533315.png)

**Comment by Alvarogd6** [comment]
Nombre de la issue modificada para incluir el diseño de la pantalla configuración. Cambiada dificultad de baja a media.

**Comment by ghost** [comment]
Diseño pantalla configuración terminado
![image](https://user-images.githubusercontent.com/44313461/80859866-28f53c00-8c64-11ea-93f6-547282785d02.png)
Se ha reducido el tamaño de la tipografía en los botones y aumentado el espacio que ocupa el boton. También se ha cambiado el boton de eliminar usuario.
Falta revisión de @Alvarogd6

**Comment by Alvarogd6** [comment]
Las pantallas de perfil y configuración ya tienen diseño y solo falta añadir lo de modificar imagen (más adelante) y suscribir a artistas (más adelante). Issue cerrada
