### ISSUE TITLE
Diseño de las pantallas de amigos

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#36]
DIseño de las pantallas en las que se muestran los amigos de un usuario, las solicitudes de amistad pendientes enviadas y las recibidas y la búsqueda de usuarios. En la pestaña de mostar amigos hay que poner un botón para eliminarlo como amigo, en las solicitudes un botón para añadir y en la búsqueda para enviar una solicitud.

**Comment by fntkg** [comment]
Diseño de la pantalla principal de amigos:

![image](https://user-images.githubusercontent.com/44313461/81055272-a4572780-8ec8-11ea-9c66-fdafcf3c1dab.png)

Falta confirmación de @Alvarogd6 

Autocrítica: no me gusta como quedan los botones de eliminar usuarios pero esque no puedo moverlos xd

**Comment by ghost** [comment]
Pantalla inicial de amigos:

![image](https://user-images.githubusercontent.com/44313461/81058932-bd170b80-8ecf-11ea-8498-1485536d0857.png)

Pantalla de solicitudes de amistad y de añadir amigos tras buscarlos:

![image](https://user-images.githubusercontent.com/44313461/81058980-d91aad00-8ecf-11ea-921f-513f117c8c83.png)

Falta revision de @Alvarogd6 

**Nota**: me gustaría poder separar el texto y los botones de la imagen del usuario pero va más alla de mis escasos conocimientos.

**Comment by Alvarogd6** [comment]
Sería mejor crear una pantalla para el buscador de usuarios en vez de encontrarse en la pantalla inicial. Otra sugerencia es que en la pantalla inicial se mostraran 3 pestañas: pantalla inicial donde se muestran los amigos del usuario, pantalla en la que se muestran las solicitudes de amistad recibidas, y la última siendo el buscador de usuarios. Requisitos extra:
- Pantalla inicial: Para cada amigo, al hacer click en ellos acceder a su perfil. También mostrar un botón para eliminarlo como amigo.
- Pantalla solicitudes de amistad recibidas: Para cada solicitud mostrar un botón para aceptar o denegar la solicitud.
- Pantalla del buscador de usuarios: Para cada usuario mostrar un botón para agregar como amigo.
- Menú lateral: Cuando el usuario se encuentre en alguna de las 3 pantallas anteriores, cambiar el fondo de la opción "Amigos" (actualmente solo está cambiado para la pantalla inicial, faltan las otras 3).

Si debido a estos requisitos ha aumentado bastante la dificultad, se aumentará la dificultad propuesta para esta issue, de media a alta.

**Comment by ghost** [comment]
Pantallas terminadas, falta revision de @Alvarogd6

**Comment by Alvarogd6** [comment]
Creada una pantalla para cada tipo enunciado en un comentario anterior y con los requisitos extra. Issue cerrada
