### ISSUE TITLE
Escalar pantalla información

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#41]
Escalar la pantalla información para diferentes tamaños de la pantalla

**Comment by ghost** [comment]
Terminado, falta revisión de @Alvarogd6

**Comment by Alvarogd6** [comment]
Cuando la pantalla sea más pequeña que el tamaño mínimo especificado, que aparezca el scroll horizontal, pero no mueva nada de la pantalla (es decir, que las imágenes y los textos no cambien de tamaño). También hay que tener en cuenta cuando la pantalla sea grande (veáse siguiente imagen, cuya solución podría ser centrar y/o aumentar el tamaño tanto de la imagen como del texto)
![Captura de pantalla de 2020-05-12 15-31-06](https://user-images.githubusercontent.com/46053417/81698319-18b03e80-9466-11ea-9729-766321f7e28c.png)

Al hacer zoom, se descuadraba el texto con la primera T metiéndose un poco debajo de la cabecera.

**Comment by ghost** [comment]
Terminado, falta revision de @Alvarogd6 

El formato no queda igual igual al aumentar que al minimizar pero creo que sirve :)
( espero que sirva porque no se hacer que se quede exactamente igual)

**Comment by Alvarogd6** [comment]
Pantalla información usable a diferentes tamaños de la pantalla. Issue cerrada
