### ISSUE TITLE
Escalar pantalla registro

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#42]
Escalar la pantalla registro a diferentes tamaños de pantalla.

**Comment by ghost** [comment]
Okey, escala de manera super extraña pero escala xd

Tienes que verlo con tus propios ojos para entender lo que digo @Alvarogd6

**Comment by Alvarogd6** [comment]
Escalar significa hacer accesible la web para diferentes tamaños de la pantalla y aquí, por lo menos cuando se hace más pequeña, el texto no es completamente legible.
Y además esto, tiene el ancho más grande de mi pantalla, pero el texto sale pequeño (la cabecera no hacía falta tocarla, y el texto se puede salir de ella)
![Captura de pantalla de 2020-05-22 13-18-32](https://user-images.githubusercontent.com/46053417/82662874-ebfee280-9c2e-11ea-8bfa-4f88a3964779.png)

**Comment by Alvarogd6** [comment]
Pantalla registro usable en diferentes tamaños de la pantalla. Issue cerrada
