### ISSUE TITLE
Escalar pantalla inicio sesión

### ISSUE THREAD

**Issue by Alvarogd6** [UNIZAR-30226-2020-10/front-end_web#43]
Escalar la pantalla de iniciar sesión para diferentes tamaños de pantalla.

**Comment by ghost** [comment]
Ya escala, no escala 100% correctamente por el tema de los iconos, pero un poco de zoom en ambos sentidos no rompe nada.

**Comment by Alvarogd6** [comment]
Pantalla de inicio sesión usable a diferentes tamaños de la pantalla. Issue cerrada
